/**
 * validate-jsonl-md-sync.js Smoke Tests
 *
 * validate-jsonl-md-sync.js is an ESM module with top-level generator
 * execution side effects. We test the pure normalize() helper logic it embeds
 * and the GENERATORS configuration structure.
 *
 * Run: npm run test:build && node --test dist-tests/tests/scripts/planning/validate-jsonl-md-sync.test.js
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";

// Mirror the normalize() function from validate-jsonl-md-sync.js
const normalize = (s: string): string =>
  s
    .replaceAll(/\*Generated by.*?\d{4}-\d{2}-\d{2}T[\d:.]+Z\*.*$/gm, "[TIMESTAMP]")
    .replaceAll(/\*\*Generated:\*\* \d{4}-\d{2}-\d{2}/gm, "**Generated:** [DATE]")
    .replaceAll(/ +$/gm, "") // strip trailing spaces only
    .trimEnd();

// =========================================================
// normalize() helper
// =========================================================

describe("normalize()", () => {
  it("replaces generated-by timestamp lines with [TIMESTAMP]", () => {
    const input = "*Generated by `gen.js` — 2025-01-15T10:30:00.000Z*";
    const result = normalize(input);
    assert.equal(result, "[TIMESTAMP]");
  });

  it("replaces generated date lines with [DATE]", () => {
    const input = "**Generated:** 2025-01-15";
    const result = normalize(input);
    assert.equal(result, "**Generated:** [DATE]");
  });

  it("strips trailing spaces from lines", () => {
    const input = "line with spaces   \nnext line  ";
    const result = normalize(input);
    assert.ok(!result.includes("   "), "trailing spaces should be stripped");
    assert.ok(result.includes("line with spaces"), "content should be preserved");
  });

  it("two documents with same content but different timestamps normalize equally", () => {
    const a = "# Header\n**Generated:** 2025-01-01\nSome content";
    const b = "# Header\n**Generated:** 2025-12-31\nSome content";
    assert.equal(normalize(a), normalize(b));
  });

  it("does not modify content that has no timestamps", () => {
    const input = "# Static Content\nNo dates here.";
    assert.equal(normalize(input), input);
  });
});
