#!/usr/bin/env node
/**
 * render-todos.js
 *
 * Generates TODOS.md from .planning/todos.jsonl.
 * JSONL is source of truth. This MD is the generated view.
 *
 * Usage:
 *   node scripts/planning/render-todos.js [--dry-run]
 *
 * Library:
 *   import { renderTodos } from "./render-todos.js";
 *   renderTodos({ dryRun: false });
 */

import { join, dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { safeWriteFileSync } from "../lib/safe-fs.js";
import { readJsonl, escapeCell } from "./lib/read-jsonl.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ROOT = resolve(__dirname, "..", "..");
const PLANNING_DIR = join(ROOT, ".planning");
const OUTPUT_FILE = join(PLANNING_DIR, "TODOS.md");

// --- Helpers ---

function esc(str) {
  return escapeCell(str);
}

const PRIORITY_ORDER = { P0: 0, P1: 1, P2: 2, P3: 3 };
const STATUS_ORDER = {
  "in-progress": 0,
  blocked: 1,
  pending: 2,
  completed: 3,
  archived: 4,
};

function sortTodos(a, b) {
  const priA = PRIORITY_ORDER[a.priority] ?? 9;
  const priB = PRIORITY_ORDER[b.priority] ?? 9;
  if (priA !== priB) return priA - priB;
  const statA = STATUS_ORDER[a.status] ?? 9;
  const statB = STATUS_ORDER[b.status] ?? 9;
  return statA - statB;
}

function formatDate(iso) {
  if (!iso) return "";
  return iso.slice(0, 10);
}

function formatTags(tags) {
  if (!tags || tags.length === 0) return "";
  return tags.join(", ");
}

/**
 * Render todos.jsonl into the TODOS.md view.
 *
 * @param {object} [opts]
 * @param {boolean} [opts.dryRun] - If true, write to stdout instead of OUTPUT_FILE
 * @param {boolean} [opts.silent] - If true, suppress the success log line
 * @returns {{ output: string, written: boolean }}
 */
export function renderTodos(opts = {}) {
  const todos = readJsonl(PLANNING_DIR, "todos.jsonl");

  const active = todos.filter((t) => !["completed", "archived"].includes(t.status)).sort(sortTodos);
  const completed = todos.filter((t) => t.status === "completed").sort(sortTodos);
  const archived = todos.filter((t) => t.status === "archived").sort(sortTodos);

  const lines = [];

  lines.push(
    "# Todos",
    "",
    "<!-- Generated by scripts/planning/render-todos.js — do not edit -->",
    ""
  );

  const counts = {
    total: todos.length,
    active: active.length,
    completed: completed.length,
    archived: archived.length,
    p0: active.filter((t) => t.priority === "P0").length,
  };
  lines.push(
    `**${counts.active} active** (${counts.p0} P0) · ${counts.completed} completed · ${counts.archived} archived`,
    ""
  );

  if (active.length > 0) {
    lines.push(
      "## Active",
      "",
      "| ID | Title | Priority | Status | Progress | Tags | Created |",
      "| --- | --- | --- | --- | --- | --- | --- |"
    );
    for (const t of active) {
      lines.push(
        `| ${esc(t.id ?? "")} | ${esc(t.title ?? "")} | ${esc(t.priority ?? "")} | ${esc(t.status ?? "")} | ${esc(t.progress ?? "")} | ${esc(formatTags(t.tags))} | ${formatDate(t.createdAt)} |`
      );
    }
    lines.push("");
  }

  if (completed.length > 0) {
    lines.push(
      "## Completed",
      "",
      "| ID | Title | Priority | Completed | Tags |",
      "| --- | --- | --- | --- | --- |"
    );
    for (const t of completed) {
      lines.push(
        `| ${esc(t.id ?? "")} | ${esc(t.title ?? "")} | ${esc(t.priority ?? "")} | ${formatDate(t.completedAt)} | ${esc(formatTags(t.tags))} |`
      );
    }
    lines.push("");
  }

  if (archived.length > 0) {
    lines.push(
      "<details>",
      `<summary>Archived (${archived.length})</summary>`,
      "",
      "| ID | Title | Priority | Tags |",
      "| --- | --- | --- | --- |"
    );
    for (const t of archived) {
      lines.push(
        `| ${esc(t.id ?? "")} | ${esc(t.title ?? "")} | ${esc(t.priority ?? "")} | ${esc(formatTags(t.tags))} |`
      );
    }
    lines.push("", "</details>", "");
  }

  const output = lines.join("\n") + "\n";

  if (opts.dryRun) {
    process.stdout.write(output);
    return { output, written: false };
  }
  safeWriteFileSync(OUTPUT_FILE, output);
  if (!opts.silent) console.log(`✓ Generated ${OUTPUT_FILE}`);
  return { output, written: true };
}

// --- Script entry point ---
// Only auto-execute when invoked directly (not when imported as a library)
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  renderTodos({ dryRun: process.argv.includes("--dry-run") });
}
